//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEXO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:include schemaLocation=&quot;nexoCommonTypes.xsd&quot; /&gt;
        ///
        ///&lt;!-- --&gt;
        ///&lt;!-- 1. Message Components Definition--&gt;
        ///&lt;!-- --&gt;
        ///
        ///  &lt;xs:simpleType name=&quot;AlgorithmTypeCode&quot;&gt;
        ///    &lt;xs:union memberTypes=&quot;AlgorithmEnumeration TypeCodeExtension&quot;/&gt;
        ///  &lt;/xs:simpleType&gt;
        ///  &lt;xs:simpleType name=&quot;AlgorithmEnumeration&quot;&gt;
        ///    &lt;xs:annotation&gt;&lt;xs:documentation&gt;Definition: Identification of a cryptographic algorithm -- Reference: RFC 3880: Internet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nexoCMS {
            get {
                return ResourceManager.GetString("nexoCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;nexo Common Schema Types V0.011 - Basic nexo types and  types used by at least two nexo protocols&lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;nexo Common Schema Types - Part 1 - Basic nexo Types&lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///  &lt;xs:simpleType name=&quot;ByteSequence&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:base64Binary [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nexoCommonTypes {
            get {
                return ResourceManager.GetString("nexoCommonTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;nexoCMS.xsd&quot;/&gt;
        ///	&lt;xs:include schemaLocation=&quot;nexoCommonTypes.xsd&quot;/&gt;
        ///
        ///	&lt;!-- --&gt;
        ///	&lt;!-- 1. Messages Definition (PDU)--&gt;
        ///	&lt;!-- --&gt;
        ///
        ///	&lt;xs:element name=&quot;SaleToPOIRequest&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Definition: Request message of the nexo Sale To POI
        ///				protocol.&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;MessageHeader&quot; type=&quot;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nexoSaleToPOIMessages {
            get {
                return ResourceManager.GetString("nexoSaleToPOIMessages", resourceCulture);
            }
        }
    }
}
