//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listener.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Listener.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error DeviceDisplay.
        /// </summary>
        internal static string DeviceDisplayAlwaysSucceed {
            get {
                return ResourceManager.GetString("DeviceDisplayAlwaysSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying predefined content [{0}].
        /// </summary>
        internal static string DisplayingPredefinedContent {
            get {
                return ResourceManager.GetString("DisplayingPredefinedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying QRcode or BarCode.
        /// </summary>
        internal static string DisplayingQRCode {
            get {
                return ResourceManager.GetString("DisplayingQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying XHTML content.
        /// </summary>
        internal static string DisplayingXHTMLContent {
            get {
                return ResourceManager.GetString("DisplayingXHTMLContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating the nexo object {0}, no more processing will occur.
        /// </summary>
        internal static string ErrorFailedCreatingTheNexoObject {
            get {
                return ResourceManager.GetString("ErrorFailedCreatingTheNexoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request parameters are not set properly, SaleID: {0}, POIID: {1}.
        /// </summary>
        internal static string ErrorInvalidRequestedIDs {
            get {
                return ResourceManager.GetString("ErrorInvalidRequestedIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested service is invalid [{0}]&quot;.
        /// </summary>
        internal static string ErrorInvalidRequestedService {
            get {
                return ResourceManager.GetString("ErrorInvalidRequestedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message can&apos;t be converted to a request [{0}].
        /// </summary>
        internal static string ErrorMessageCantBeConvertedToRequest {
            get {
                return ResourceManager.GetString("ErrorMessageCantBeConvertedToRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested POI [{0}] doesn&apos;t exist, The request will not be carried out&quot;.
        /// </summary>
        internal static string ErrorRequestedPOIDoesntExist {
            get {
                return ResourceManager.GetString("ErrorRequestedPOIDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested service is not allowed [{0}].
        /// </summary>
        internal static string ErrorRequestedServiceNotAllowed {
            get {
                return ResourceManager.GetString("ErrorRequestedServiceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid display device request [{0}].
        /// </summary>
        internal static string InvalidDisplayDevice {
            get {
                return ResourceManager.GetString("InvalidDisplayDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;is missing&gt;.
        /// </summary>
        internal static string IsMissing {
            get {
                return ResourceManager.GetString("IsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log from SaleID {0} to POIID {1}.
        /// </summary>
        internal static string LoginFailedToLogTo {
            get {
                return ResourceManager.GetString("LoginFailedToLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged to POI.
        /// </summary>
        internal static string LoginSucceeded {
            get {
                return ResourceManager.GetString("LoginSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to log from SaleID {0} to POIID {1}.
        /// </summary>
        internal static string LoginTryingToLogWith {
            get {
                return ResourceManager.GetString("LoginTryingToLogWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out SaleID {0} from POIID {1}.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort request has not been processed.
        /// </summary>
        internal static string NotificationAbortHasNotBeenProcessed {
            get {
                return ResourceManager.GetString("NotificationAbortHasNotBeenProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification for event {0} [{1}].
        /// </summary>
        internal static string NotificationForEvent {
            get {
                return ResourceManager.GetString("NotificationForEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification processed through miscellaneous processing.
        /// </summary>
        internal static string NotificationMiscellaneousProcessing {
            get {
                return ResourceManager.GetString("NotificationMiscellaneousProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI access has been granted.
        /// </summary>
        internal static string POIAccessHasBeenGranted {
            get {
                return ResourceManager.GetString("POIAccessHasBeenGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI is already in use.
        /// </summary>
        internal static string POIIsAlreadyInUse {
            get {
                return ResourceManager.GetString("POIIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation manually cancelled while processing {0} service.
        /// </summary>
        internal static string ProcessingCancelled {
            get {
                return ResourceManager.GetString("ProcessingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to POI.
        /// </summary>
        internal static string ProcessingConnectedToPOI {
            get {
                return ResourceManager.GetString("ProcessingConnectedToPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the POI at {0}, no more processing can be made.
        /// </summary>
        internal static string ProcessingErrorConnectingToPOI {
            get {
                return ResourceManager.GetString("ProcessingErrorConnectingToPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to exchange the nexo retailer {0} order.
        /// </summary>
        internal static string ProcessingErrorWhileExchange {
            get {
                return ResourceManager.GetString("ProcessingErrorWhileExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to log to the POI.
        /// </summary>
        internal static string ProcessingErrorWhileLogin {
            get {
                return ResourceManager.GetString("ProcessingErrorWhileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occurred while processing the request [{0}].
        /// </summary>
        internal static string ProcessingException {
            get {
                return ResourceManager.GetString("ProcessingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} ended with a noMoreAction status.
        /// </summary>
        internal static string ProcessingNoMoreAction {
            get {
                return ResourceManager.GetString("ProcessingNoMoreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an reply for service {0}.
        /// </summary>
        internal static string ProcessingReceived {
            get {
                return ResourceManager.GetString("ProcessingReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing of service {0} ended up with {1} result {2}.
        /// </summary>
        internal static string ProcessingResult {
            get {
                return ResourceManager.GetString("ProcessingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout receiving the response to {0} request.
        /// </summary>
        internal static string ProcessingTimeout {
            get {
                return ResourceManager.GetString("ProcessingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error while processing {0} service.
        /// </summary>
        internal static string ProcessingUnknowError {
            get {
                return ResourceManager.GetString("ProcessingUnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} completed.
        /// </summary>
        internal static string ServiceCompleted {
            get {
                return ResourceManager.GetString("ServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service {0}.
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
    }
}
