//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listener.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Listener.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error DeviceDisplay.
        /// </summary>
        internal static string DeviceDisplayAlwaysSucceed {
            get {
                return ResourceManager.GetString("DeviceDisplayAlwaysSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying predefined content [{0}].
        /// </summary>
        internal static string DisplayingPredefinedContent {
            get {
                return ResourceManager.GetString("DisplayingPredefinedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying QRcode or BarCode.
        /// </summary>
        internal static string DisplayingQRCode {
            get {
                return ResourceManager.GetString("DisplayingQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying XHTML content.
        /// </summary>
        internal static string DisplayingXHTMLContent {
            get {
                return ResourceManager.GetString("DisplayingXHTMLContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid display device request [{0}].
        /// </summary>
        internal static string InvalidDisplayDevice {
            get {
                return ResourceManager.GetString("InvalidDisplayDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log from SaleID {0} to POIID {1}.
        /// </summary>
        internal static string LoginFailedToLogTo {
            get {
                return ResourceManager.GetString("LoginFailedToLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to log from SaleID {0} to POIID {1}.
        /// </summary>
        internal static string LoginTryingToLogWith {
            get {
                return ResourceManager.GetString("LoginTryingToLogWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out SaleID {0} from POIID {1}.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort request has not been processed.
        /// </summary>
        internal static string NotificationAbortHasNotBeenProcessed {
            get {
                return ResourceManager.GetString("NotificationAbortHasNotBeenProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification for event {0} [{1}].
        /// </summary>
        internal static string NotificationForEvent {
            get {
                return ResourceManager.GetString("NotificationForEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification processed through miscellaneous processing.
        /// </summary>
        internal static string NotificationMiscellaneousProcessing {
            get {
                return ResourceManager.GetString("NotificationMiscellaneousProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI access has been granted.
        /// </summary>
        internal static string POIAccessHasBeenGranted {
            get {
                return ResourceManager.GetString("POIAccessHasBeenGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI is already in use.
        /// </summary>
        internal static string POIIsAlreadyInUse {
            get {
                return ResourceManager.GetString("POIIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} completed.
        /// </summary>
        internal static string ServiceCompleted {
            get {
                return ResourceManager.GetString("ServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service {0}.
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
    }
}
