//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listener.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Listener.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection has been cancelled.
        /// </summary>
        internal static string ConnectionHasBeenCancelled {
            get {
                return ResourceManager.GetString("ConnectionHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error DeviceDisplay.
        /// </summary>
        internal static string DeviceDisplayAlwaysSucceed {
            get {
                return ResourceManager.GetString("DeviceDisplayAlwaysSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        internal static string DisplayAddress {
            get {
                return ResourceManager.GetString("DisplayAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener connection to EListener server process failed to start, shutting down.
        /// </summary>
        internal static string DisplayFailedToConnectToEListener {
            get {
                return ResourceManager.GetString("DisplayFailedToConnectToEListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read settings.
        /// </summary>
        internal static string DisplayFailedToReadSettings {
            get {
                return ResourceManager.GetString("DisplayFailedToReadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener WS interface failed to start, shutting down.
        /// </summary>
        internal static string DisplayFailedToStartWSInterface {
            get {
                return ResourceManager.GetString("DisplayFailedToStartWSInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying predefined content [{0}].
        /// </summary>
        internal static string DisplayingPredefinedContent {
            get {
                return ResourceManager.GetString("DisplayingPredefinedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying QRcode or BarCode.
        /// </summary>
        internal static string DisplayingQRCode {
            get {
                return ResourceManager.GetString("DisplayingQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying XHTML content.
        /// </summary>
        internal static string DisplayingXHTMLContent {
            get {
                return ResourceManager.GetString("DisplayingXHTMLContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        internal static string DisplayLogFile {
            get {
                return ResourceManager.GetString("DisplayLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to read settings from.
        /// </summary>
        internal static string DisplayStarting {
            get {
                return ResourceManager.GetString("DisplayStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert {0} in the list of current clients.
        /// </summary>
        internal static string ERROR_FailedToAddWSClient {
            get {
                return ResourceManager.GetString("ERROR_FailedToAddWSClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The listener process connected to WS server has terminated, shutting down.
        /// </summary>
        internal static string ERROR_WSClientHasStopped {
            get {
                return ResourceManager.GetString("ERROR_WSClientHasStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener WS interface failed to start.
        /// </summary>
        internal static string ERROR_WSInterfaceNotStarted {
            get {
                return ResourceManager.GetString("ERROR_WSInterfaceNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating the nexo object {0}, no more processing will occur.
        /// </summary>
        internal static string ErrorFailedCreatingTheNexoObject {
            get {
                return ResourceManager.GetString("ErrorFailedCreatingTheNexoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request parameters are not set properly, SaleID: {0}, POIID: {1}.
        /// </summary>
        internal static string ErrorInvalidRequestedIDs {
            get {
                return ResourceManager.GetString("ErrorInvalidRequestedIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested service is invalid [{0}]&quot;.
        /// </summary>
        internal static string ErrorInvalidRequestedService {
            get {
                return ResourceManager.GetString("ErrorInvalidRequestedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message can&apos;t be converted to a request [{0}].
        /// </summary>
        internal static string ErrorMessageCantBeConvertedToRequest {
            get {
                return ResourceManager.GetString("ErrorMessageCantBeConvertedToRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested POI [{0}] doesn&apos;t exist, The request will not be carried out&quot;.
        /// </summary>
        internal static string ErrorRequestedPOIDoesntExist {
            get {
                return ResourceManager.GetString("ErrorRequestedPOIDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested service is not allowed [{0}].
        /// </summary>
        internal static string ErrorRequestedServiceNotAllowed {
            get {
                return ResourceManager.GetString("ErrorRequestedServiceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed saving incoming connection to list of current clients.
        /// </summary>
        internal static string FailedInsertingConnectedClient {
            get {
                return ResourceManager.GetString("FailedInsertingConnectedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting listener WS interface.
        /// </summary>
        internal static string INFOR_StartingWSInterface {
            get {
                return ResourceManager.GetString("INFOR_StartingWSInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating the data path {0}, that data won&apos;t be set.
        /// </summary>
        internal static string InputDataFailedCreatingPath {
            get {
                return ResourceManager.GetString("InputDataFailedCreatingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed settings data {0} to value {1}.
        /// </summary>
        internal static string InputDataFailedToSetData {
            get {
                return ResourceManager.GetString("InputDataFailedToSetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid display device request [{0}].
        /// </summary>
        internal static string InvalidDisplayDevice {
            get {
                return ResourceManager.GetString("InvalidDisplayDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;is missing&gt;.
        /// </summary>
        internal static string IsMissing {
            get {
                return ResourceManager.GetString("IsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log from SaleID {0} to POIID {1}.
        /// </summary>
        internal static string LoginFailedToLogTo {
            get {
                return ResourceManager.GetString("LoginFailedToLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged to POI.
        /// </summary>
        internal static string LoginSucceeded {
            get {
                return ResourceManager.GetString("LoginSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to log from SaleID {0} to POIID {1}.
        /// </summary>
        internal static string LoginTryingToLogWith {
            get {
                return ResourceManager.GetString("LoginTryingToLogWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out SaleID {0} from POIID {1}.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while running {0}.
        /// </summary>
        internal static string NeptingError {
            get {
                return ResourceManager.GetString("NeptingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating a Nepting message.
        /// </summary>
        internal static string NeptingFailedCreatingMessage {
            get {
                return ResourceManager.GetString("NeptingFailedCreatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested field {0} with index {1} was not found in the message.
        /// </summary>
        internal static string NeptingFieldIndexNotPresent {
            get {
                return ResourceManager.GetString("NeptingFieldIndexNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested field {0} was not found in the message.
        /// </summary>
        internal static string NeptingFieldNotPresent {
            get {
                return ResourceManager.GetString("NeptingFieldNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection type specified ({0}).
        /// </summary>
        internal static string NeptingInvalidConnectionType {
            get {
                return ResourceManager.GetString("NeptingInvalidConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid log file size({0}).
        /// </summary>
        internal static string NeptingInvalidLogFileSize {
            get {
                return ResourceManager.GetString("NeptingInvalidLogFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified log level is invalid ({0}).
        /// </summary>
        internal static string NeptingInvalidLogLevel {
            get {
                return ResourceManager.GetString("NeptingInvalidLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path or not writeable ({0}).
        /// </summary>
        internal static string NeptingInvalidPath {
            get {
                return ResourceManager.GetString("NeptingInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active connection to a Nepting terminal.
        /// </summary>
        internal static string NeptingIsNotConnected {
            get {
                return ResourceManager.GetString("NeptingIsNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nepting link is not ready, function {0} can&apos;t be executed.
        /// </summary>
        internal static string NeptingIsNotReady {
            get {
                return ResourceManager.GetString("NeptingIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nepting link is already setup, function {0} can&apos;t be executed.
        /// </summary>
        internal static string NeptingIsReady {
            get {
                return ResourceManager.GetString("NeptingIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No field name was specified to add to the message.
        /// </summary>
        internal static string NeptingNoFieldName {
            get {
                return ResourceManager.GetString("NeptingNoFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No field value was specified to add to the message for field {0}.
        /// </summary>
        internal static string NeptingNoFieldValue {
            get {
                return ResourceManager.GetString("NeptingNoFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message has been created.
        /// </summary>
        internal static string NeptingNoMessage {
            get {
                return ResourceManager.GetString("NeptingNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout receiving a message.
        /// </summary>
        internal static string NeptingTimeoutReceiving {
            get {
                return ResourceManager.GetString("NeptingTimeoutReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort request has not been processed.
        /// </summary>
        internal static string NotificationAbortHasNotBeenProcessed {
            get {
                return ResourceManager.GetString("NotificationAbortHasNotBeenProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification for event {0} [{1}].
        /// </summary>
        internal static string NotificationForEvent {
            get {
                return ResourceManager.GetString("NotificationForEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification processed through miscellaneous processing.
        /// </summary>
        internal static string NotificationMiscellaneousProcessing {
            get {
                return ResourceManager.GetString("NotificationMiscellaneousProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating return data path for {0}, that data won&apos;t be fetched.
        /// </summary>
        internal static string OutputDataFailedCreatingPath {
            get {
                return ResourceManager.GetString("OutputDataFailedCreatingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed fetching output data {0}.
        /// </summary>
        internal static string OutputDataFailedFetchingData {
            get {
                return ResourceManager.GetString("OutputDataFailedFetchingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI access has been granted.
        /// </summary>
        internal static string POIAccessHasBeenGranted {
            get {
                return ResourceManager.GetString("POIAccessHasBeenGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI is already in use.
        /// </summary>
        internal static string POIIsAlreadyInUse {
            get {
                return ResourceManager.GetString("POIIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings.
        /// </summary>
        internal static string POISConnectionSettings {
            get {
                return ResourceManager.GetString("POISConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation manually cancelled while processing {0} service.
        /// </summary>
        internal static string ProcessingCancelled {
            get {
                return ResourceManager.GetString("ProcessingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to POI.
        /// </summary>
        internal static string ProcessingConnectedToPOI {
            get {
                return ResourceManager.GetString("ProcessingConnectedToPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the POI at {0}, no more processing can be made.
        /// </summary>
        internal static string ProcessingErrorConnectingToPOI {
            get {
                return ResourceManager.GetString("ProcessingErrorConnectingToPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to exchange the nexo retailer {0} order.
        /// </summary>
        internal static string ProcessingErrorWhileExchange {
            get {
                return ResourceManager.GetString("ProcessingErrorWhileExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to log to the POI.
        /// </summary>
        internal static string ProcessingErrorWhileLogin {
            get {
                return ResourceManager.GetString("ProcessingErrorWhileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occurred while processing the request [{0}].
        /// </summary>
        internal static string ProcessingException {
            get {
                return ResourceManager.GetString("ProcessingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found card brand: {0}.
        /// </summary>
        internal static string ProcessingFoundCardBrand {
            get {
                return ResourceManager.GetString("ProcessingFoundCardBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} ended with a noMoreAction status.
        /// </summary>
        internal static string ProcessingNoMoreAction {
            get {
                return ResourceManager.GetString("ProcessingNoMoreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing auto-login.
        /// </summary>
        internal static string ProcessingPerformingAutoLogin {
            get {
                return ResourceManager.GetString("ProcessingPerformingAutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing auto-logout.
        /// </summary>
        internal static string ProcessingPerformingAutoLogout {
            get {
                return ResourceManager.GetString("ProcessingPerformingAutoLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an reply for service {0}.
        /// </summary>
        internal static string ProcessingReceived {
            get {
                return ResourceManager.GetString("ProcessingReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing of service {0} ended up with {1} result {2}.
        /// </summary>
        internal static string ProcessingResult {
            get {
                return ResourceManager.GetString("ProcessingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message to eListener [{0}].
        /// </summary>
        internal static string ProcessingSendingAnswerToServer {
            get {
                return ResourceManager.GetString("ProcessingSendingAnswerToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout receiving the response to {0} request.
        /// </summary>
        internal static string ProcessingTimeout {
            get {
                return ResourceManager.GetString("ProcessingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error while processing {0} service.
        /// </summary>
        internal static string ProcessingUnknowError {
            get {
                return ResourceManager.GetString("ProcessingUnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received message.
        /// </summary>
        internal static string ReceivedMessage {
            get {
                return ResourceManager.GetString("ReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending login result: {0}.
        /// </summary>
        internal static string SendingLoginResult {
            get {
                return ResourceManager.GetString("SendingLoginResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} completed.
        /// </summary>
        internal static string ServiceCompleted {
            get {
                return ResourceManager.GetString("ServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service {0}.
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Process.
        /// </summary>
        internal static string ThreadNameHTTP {
            get {
                return ResourceManager.GetString("ThreadNameHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Process.
        /// </summary>
        internal static string ThreadNameWS {
            get {
                return ResourceManager.GetString("ThreadNameWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener WS interface started.
        /// </summary>
        internal static string TRACE_WSInterfaceStarted {
            get {
                return ResourceManager.GetString("TRACE_WSInterfaceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client listener trying to connect to {0} (attempt {1})&quot;.
        /// </summary>
        internal static string WSClientConnectingToServer {
            get {
                return ResourceManager.GetString("WSClientConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client listener failed to connect to the WS server at {0}, another attempt will be made in {1} seconds.
        /// </summary>
        internal static string WSClientFailedToConnect {
            get {
                return ResourceManager.GetString("WSClientFailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client listener is connected to {0}.
        /// </summary>
        internal static string WSClientIsConnected {
            get {
                return ResourceManager.GetString("WSClientIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client listener has been terminated, shutting down.
        /// </summary>
        internal static string WSClientTerminated {
            get {
                return ResourceManager.GetString("WSClientTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to listener at {0}.
        /// </summary>
        internal static string WSInterfaceConnectedToListener {
            get {
                return ResourceManager.GetString("WSInterfaceConnectedToListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection from {0} has been closed.
        /// </summary>
        internal static string WSInterfaceConnectionHasBeenClosed {
            get {
                return ResourceManager.GetString("WSInterfaceConnectionHasBeenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS interface disconnected.
        /// </summary>
        internal static string WSInterfaceDisconnected {
            get {
                return ResourceManager.GetString("WSInterfaceDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sending data to the listener.
        /// </summary>
        internal static string WSInterfaceFailedSendingDataToListener {
            get {
                return ResourceManager.GetString("WSInterfaceFailedSendingDataToListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed connecting to the processing server.
        /// </summary>
        internal static string WSInterfaceFailedToConnectToListener {
            get {
                return ResourceManager.GetString("WSInterfaceFailedToConnectToListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming connection.
        /// </summary>
        internal static string WSInterfaceIncomingConnection {
            get {
                return ResourceManager.GetString("WSInterfaceIncomingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to WS interface denied.
        /// </summary>
        internal static string WSInterfaceLoginKO {
            get {
                return ResourceManager.GetString("WSInterfaceLoginKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to WS interface granted.
        /// </summary>
        internal static string WSInterfaceLoginOK {
            get {
                return ResourceManager.GetString("WSInterfaceLoginOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received HTTP request, connection is being closed with status {0}.
        /// </summary>
        internal static string WSInterfaceNotWSRequest {
            get {
                return ResourceManager.GetString("WSInterfaceNotWSRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received security details: {0}.
        /// </summary>
        internal static string WSInterfaceReceivedSecurityDetails {
            get {
                return ResourceManager.GetString("WSInterfaceReceivedSecurityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The listener WS interface stopped with result code {0}.
        /// </summary>
        internal static string WSInterfaceStopped {
            get {
                return ResourceManager.GetString("WSInterfaceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting incoming data.
        /// </summary>
        internal static string WSInterfaceWaitingForIncomingData {
            get {
                return ResourceManager.GetString("WSInterfaceWaitingForIncomingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting security details.
        /// </summary>
        internal static string WSInterfaceWaitingSecurityDetails {
            get {
                return ResourceManager.GetString("WSInterfaceWaitingSecurityDetails", resourceCulture);
            }
        }
    }
}
