//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listener.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Listener.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit ?.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to return.
        /// </summary>
        internal static string DataToReturn {
            get {
                return ResourceManager.GetString("DataToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to send.
        /// </summary>
        internal static string DataToSend {
            get {
                return ResourceManager.GetString("DataToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC.
        /// </summary>
        internal static string ESC {
            get {
                return ResourceManager.GetString("ESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failes read listener settings ({0}).
        /// </summary>
        internal static string FailedReadListenerSettings {
            get {
                return ResourceManager.GetString("FailedReadListenerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed read settings in registry.
        /// </summary>
        internal static string FailedReadRegistry {
            get {
                return ResourceManager.GetString("FailedReadRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sending the request.
        /// </summary>
        internal static string FailedSendingRequest {
            get {
                return ResourceManager.GetString("FailedSendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to use.
        /// </summary>
        internal static string FileToUse {
            get {
                return ResourceManager.GetString("FileToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP.
        /// </summary>
        internal static string InvalidIP {
            get {
                return ResourceManager.GetString("InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port number.
        /// </summary>
        internal static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid test file.
        /// </summary>
        internal static string InvalidTestFile {
            get {
                return ResourceManager.GetString("InvalidTestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WS extension.
        /// </summary>
        internal static string InvalidWSMap {
            get {
                return ResourceManager.GetString("InvalidWSMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener IP.
        /// </summary>
        internal static string ListenerIP {
            get {
                return ResourceManager.GetString("ListenerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener port to reach.
        /// </summary>
        internal static string ListenerPort {
            get {
                return ResourceManager.GetString("ListenerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display settings.
        /// </summary>
        internal static string MenuDisplaySettings {
            get {
                return ResourceManager.GetString("MenuDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate listener test file.
        /// </summary>
        internal static string MenuGenerateListenerTestFile {
            get {
                return ResourceManager.GetString("MenuGenerateListenerTestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload settings.
        /// </summary>
        internal static string MenuReloadSettings {
            get {
                return ResourceManager.GetString("MenuReloadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Listener.
        /// </summary>
        internal static string MenuStartListener {
            get {
                return ResourceManager.GetString("MenuStartListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Listener.
        /// </summary>
        internal static string MenuStopListener {
            get {
                return ResourceManager.GetString("MenuStopListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test listener.
        /// </summary>
        internal static string MenuTestListener {
            get {
                return ResourceManager.GetString("MenuTestListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoL {
            get {
                return ResourceManager.GetString("NoL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Payment (otherwise it will be a Refund).
        /// </summary>
        internal static string NormalPaymentOrRefund {
            get {
                return ResourceManager.GetString("NormalPaymentOrRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string NoS {
            get {
                return ResourceManager.GetString("NoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI ID.
        /// </summary>
        internal static string POIID {
            get {
                return ResourceManager.GetString("POIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POIToReach.
        /// </summary>
        internal static string POIToReach {
            get {
                return ResourceManager.GetString("POIToReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to received message from the listener.
        /// </summary>
        internal static string ReceivedMessage {
            get {
                return ResourceManager.GetString("ReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer service to call.
        /// </summary>
        internal static string RetailerServiceToCall {
            get {
                return ResourceManager.GetString("RetailerServiceToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale ID.
        /// </summary>
        internal static string SaleID {
            get {
                return ResourceManager.GetString("SaleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message sent to listener, timeout is {0} seconds.
        /// </summary>
        internal static string SentMessage {
            get {
                return ResourceManager.GetString("SentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A test file called {0} already exists, do you want to override it ?.
        /// </summary>
        internal static string TestFileAlreadyExists {
            get {
                return ResourceManager.GetString("TestFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file to use.
        /// </summary>
        internal static string TestFileToUse {
            get {
                return ResourceManager.GetString("TestFileToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Web Socket with the listener ?.
        /// </summary>
        internal static string UseWS {
            get {
                return ResourceManager.GetString("UseWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using settings file: {0}.
        /// </summary>
        internal static string UsingSettingsFile {
            get {
                return ResourceManager.GetString("UsingSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0}.
        /// </summary>
        internal static string ValueFor {
            get {
                return ResourceManager.GetString("ValueFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS extension.
        /// </summary>
        internal static string WSMap {
            get {
                return ResourceManager.GetString("WSMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesL {
            get {
                return ResourceManager.GetString("YesL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YesS {
            get {
                return ResourceManager.GetString("YesS", resourceCulture);
            }
        }
    }
}
