//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listener.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Listener.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener is connected to WS server {0}.
        /// </summary>
        internal static string WorkerConnectedToWSServer {
            get {
                return ResourceManager.GetString("WorkerConnectedToWSServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener is trying to connect to WS server {0}.
        /// </summary>
        internal static string WorkerConnectingToWSServer {
            get {
                return ResourceManager.GetString("WorkerConnectingToWSServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener connection to WS {0} is pending.
        /// </summary>
        internal static string WorkerConnectionToWSServerIsPending {
            get {
                return ResourceManager.GetString("WorkerConnectionToWSServerIsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener is disconnected from WS server {0}.
        /// </summary>
        internal static string WorkerDisconnectedFromWSServer {
            get {
                return ResourceManager.GetString("WorkerDisconnectedFromWSServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener is logged to WS server {0}.
        /// </summary>
        internal static string WorkerLogged {
            get {
                return ResourceManager.GetString("WorkerLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login in to WS server {0} has been denied.
        /// </summary>
        internal static string WorkerLoginDenied {
            get {
                return ResourceManager.GetString("WorkerLoginDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener is trying to log to WS server {0}.
        /// </summary>
        internal static string WorkerLoginToWSServer {
            get {
                return ResourceManager.GetString("WorkerLoginToWSServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener process not started.
        /// </summary>
        internal static string WorkerProcessesNotStarted {
            get {
                return ResourceManager.GetString("WorkerProcessesNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener processes started.
        /// </summary>
        internal static string WorkerProcessesStarted {
            get {
                return ResourceManager.GetString("WorkerProcessesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener processes stopped.
        /// </summary>
        internal static string WorkerProcessesStopped {
            get {
                return ResourceManager.GetString("WorkerProcessesStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service did not start successfully and is stopping.
        /// </summary>
        internal static string WorkerServiceDidNotStart {
            get {
                return ResourceManager.GetString("WorkerServiceDidNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service {0} is running.
        /// </summary>
        internal static string WorkerServiceIsRunning {
            get {
                return ResourceManager.GetString("WorkerServiceIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service is starting.
        /// </summary>
        internal static string WorkerServiceIsStarting {
            get {
                return ResourceManager.GetString("WorkerServiceIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service is stopped.
        /// </summary>
        internal static string WorkerServiceIsStopped {
            get {
                return ResourceManager.GetString("WorkerServiceIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service is stopping.
        /// </summary>
        internal static string WorkerServiceIsStopping {
            get {
                return ResourceManager.GetString("WorkerServiceIsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service not started.
        /// </summary>
        internal static string WorkerServiceNotStarted {
            get {
                return ResourceManager.GetString("WorkerServiceNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting listener processes.
        /// </summary>
        internal static string WorkerStartingProcesses {
            get {
                return ResourceManager.GetString("WorkerStartingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopping listener processes.
        /// </summary>
        internal static string WorkerStoppingProcesses {
            get {
                return ResourceManager.GetString("WorkerStoppingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listener is disconnecting from WS server {0}.
        /// </summary>
        internal static string WorketDisconnectingFromWSServer {
            get {
                return ResourceManager.GetString("WorketDisconnectingFromWSServer", resourceCulture);
            }
        }
    }
}
