//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NexoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NexoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexoResources.Properties.NexoResources", typeof(NexoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:include schemaLocation=&quot;EpasCommonTypes.xsd&quot; /&gt;
        ///
        ///&lt;!-- --&gt;
        ///&lt;!-- 1. Message Components Definition--&gt;
        ///&lt;!-- --&gt;
        ///
        ///  &lt;xs:simpleType name=&quot;AlgorithmTypeCode&quot;&gt;
        ///    &lt;xs:union memberTypes=&quot;AlgorithmEnumeration TypeCodeExtension&quot;/&gt;
        ///  &lt;/xs:simpleType&gt;
        ///  &lt;xs:simpleType name=&quot;AlgorithmEnumeration&quot;&gt;
        ///    &lt;xs:annotation&gt;&lt;xs:documentation&gt;Definition: Identification of a cryptographic algorithm -- Reference: RFC 38 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo30CMS {
            get {
                return ResourceManager.GetString("nexo30CMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;EPAS Common Schema Types V0.011 - Basic EPAS types and  types used by at least two EPAS protocols&lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;EPAS Common Schema Types - Part 1 - Basic EPAS Types&lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///  &lt;xs:simpleType name=&quot;ByteSequence&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:bas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo30CommonTypes {
            get {
                return ResourceManager.GetString("nexo30CommonTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;EpasCMS.xsd&quot; /&gt;
        ///	&lt;xs:include schemaLocation=&quot;EpasCommonTypes.xsd&quot; /&gt;
        ///
        ///	&lt;!-- --&gt;
        ///	&lt;!-- 1. Messages Definition (PDU)--&gt;
        ///	&lt;!-- --&gt;
        ///
        ///	&lt;xs:element name=&quot;SaleToPOIRequest&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Definition: Request message of the EPAS Sale To POI protocol.&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;MessageHe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo30SaleToPOIMessages {
            get {
                return ResourceManager.GetString("nexo30SaleToPOIMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:include schemaLocation=&quot;nexoCommonTypes.xsd&quot; /&gt;
        ///
        ///&lt;!-- --&gt;
        ///&lt;!-- 1. Message Components Definition--&gt;
        ///&lt;!-- --&gt;
        ///
        ///  &lt;xs:simpleType name=&quot;AlgorithmTypeCode&quot;&gt;
        ///    &lt;xs:union memberTypes=&quot;AlgorithmEnumeration TypeCodeExtension&quot;/&gt;
        ///  &lt;/xs:simpleType&gt;
        ///  &lt;xs:simpleType name=&quot;AlgorithmEnumeration&quot;&gt;
        ///    &lt;xs:annotation&gt;&lt;xs:documentation&gt;Definition: Identification of a cryptographic algorithm -- Reference: RFC 38 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo31CMS {
            get {
                return ResourceManager.GetString("nexo31CMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;nexo Common Schema Types V0.011 - Basic nexo types and  types used by at least two nexo protocols&lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;nexo Common Schema Types - Part 1 - Basic nexo Types&lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///  &lt;xs:simpleType name=&quot;ByteSequence&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:bas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo31CommonTypes {
            get {
                return ResourceManager.GetString("nexo31CommonTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;nexoCMS.xsd&quot;/&gt;
        ///	&lt;xs:include schemaLocation=&quot;nexoCommonTypes.xsd&quot;/&gt;
        ///
        ///	&lt;!-- --&gt;
        ///	&lt;!-- 1. Messages Definition (PDU)--&gt;
        ///	&lt;!-- --&gt;
        ///
        ///	&lt;xs:element name=&quot;SaleToPOIRequest&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Definition: Request message of the nexo Sale To POI
        ///				protocol.&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;Messag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo31SaleToPOIMessages {
            get {
                return ResourceManager.GetString("nexo31SaleToPOIMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.001.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.001.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_001_001_01 {
            get {
                return ResourceManager.GetString("nexo40_001_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.002.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.002.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_002_001_01 {
            get {
                return ResourceManager.GetString("nexo40_002_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.003.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.003.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_003_001_01 {
            get {
                return ResourceManager.GetString("nexo40_003_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.004.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.004.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_004_001_01 {
            get {
                return ResourceManager.GetString("nexo40_004_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.005.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.005.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_005_001_01 {
            get {
                return ResourceManager.GetString("nexo40_005_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.006.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.006.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_006_001_01 {
            get {
                return ResourceManager.GetString("nexo40_006_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.007.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.007.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_007_001_01 {
            get {
                return ResourceManager.GetString("nexo40_007_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.008.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.008.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_008_001_01 {
            get {
                return ResourceManager.GetString("nexo40_008_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.009.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.009.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_009_001_01 {
            get {
                return ResourceManager.GetString("nexo40_009_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.010.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.010.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_010_001_01 {
            get {
                return ResourceManager.GetString("nexo40_010_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.011.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.011.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;AbortData1&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;XchgId&quot; type=&quot;Ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_011_001_01 {
            get {
                return ResourceManager.GetString("nexo40_011_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.012.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.012.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_012_001_01 {
            get {
                return ResourceManager.GetString("nexo40_012_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.013.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.013.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;AcceptorRejection2&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;RjctRsn&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_013_001_01 {
            get {
                return ResourceManager.GetString("nexo40_013_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.014.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.014.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_014_001_01 {
            get {
                return ResourceManager.GetString("nexo40_014_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.015.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.015.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_015_001_01 {
            get {
                return ResourceManager.GetString("nexo40_015_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.016.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.016.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_016_001_01 {
            get {
                return ResourceManager.GetString("nexo40_016_001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Generated by Standards Editor (build:R1.6.16) on 2019 Jun 12 11:51:20, ISO 20022 version : 2013--&gt;
        ///&lt;xs:schema xmlns=&quot;urn:iso:std:iso:20022:tech:xsd:casp.017.001.01&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;urn:iso:std:iso:20022:tech:xsd:casp.017.001.01&quot;&gt;
        ///    &lt;xs:element name=&quot;Document&quot; type=&quot;Document&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;Acquirer9&quot;&gt;
        ///        &lt;xs:sequence&gt;
        ///            &lt;xs:element name=&quot;Id&quot; type=&quot;Generic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nexo40_017_001_01 {
            get {
                return ResourceManager.GetString("nexo40_017_001_01", resourceCulture);
            }
        }
    }
}
