using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
using COMMON;

namespace NEXO
{
	[ComVisible(false)]
	class NexoErrors
	{
		public static string Aborted(NexoResponseType r, string status, string abortreason, string saleid, string serviceid) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.ErrorCondition = ErrorConditionEnumeration.Aborted; r.AdditionalResponse = "Service aborted during " + status + " - Reason+: " + abortreason + " - From: " + saleid + " - Message ID: " + serviceid; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string Busy(NexoResponseType r, string msg) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.Busy; r.AdditionalResponse = "System busy: " + msg; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string BusyComponentUnavailable(NexoResponseType r, string component, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.Busy; r.AdditionalResponse = "POI " + component + " temporary unavailable: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string BusyPOIBusy(NexoResponseType r, string request) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.Busy; r.AdditionalResponse = "POI terminal busy processing another request: " + request; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string BusyDeviceBusy(NexoResponseType r, string system, string device) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.Busy; r.AdditionalResponse = system + " terminal " + device + " busy processing the device request"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string CancelUserCancellation(NexoResponseType r, string status) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.Cancel; r.AdditionalResponse = "User cancellation during " + status; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string CancelSystemCancellation(NexoResponseType r, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.Cancel; r.AdditionalResponse = "System cancellation during " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string DeviceOutPOITemporaryUnavailable(NexoResponseType r, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.DeviceOut; r.AdditionalResponse = "POI is temporary unavailable: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string DeviceOutPOIPermanentlyUnavailable(NexoResponseType r, string device, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.DeviceOut; r.AdditionalResponse = "POI " + device + " is permanently unavailable: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string DeviceOutDeviceTemporaryOut(NexoResponseType r, string device, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.DeviceOut; r.AdditionalResponse = device + " is temporarily out of service: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string DeviceOutDevicePermanentlyOut(NexoResponseType r, string device, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.DeviceOut; r.AdditionalResponse = device + " is permanently out of service: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string DeviceOutMaintenance(NexoResponseType r, string device, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.DeviceOut; r.AdditionalResponse = device + " Maintenance: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string DeviceOutSecurityAlarm(NexoResponseType r, string alarm) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.DeviceOut; r.AdditionalResponse = "Security alarm: " + alarm; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string InProgress(NexoResponseType r) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.InProgress; r.AdditionalResponse = "Uncompleted Transaction"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string InsertedCard(NexoResponseType r) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.InsertedCard; r.AdditionalResponse = "Not user input"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string InsertedCardNoCardEntered(NexoResponseType r, string seconds) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.InsertedCard; r.AdditionalResponse = "No Card entered after " + seconds + " seconds"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string InsertedCardUnreadableCard(NexoResponseType r, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.InsertedCard; r.AdditionalResponse = "Card can't be read: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string InsertedCardUnknownCard(NexoResponseType r, string binaid) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.InsertedCard; r.AdditionalResponse = "Unknown card : " + binaid; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string InsertedCardInvalidCard(NexoResponseType r, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.InsertedCard; r.AdditionalResponse = "Card invalid: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string LoggedOut(NexoResponseType r, string saleid, string evt, DateTime time) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.LoggedOut; r.AdditionalResponse = saleid + " never logged since last " + evt + " at " + time.ToString(Chars.DATETIME); CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string MessageFormatGeneralParsingError(NexoResponseType r, string absolutedataname, string error) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "General parsing error: " + absolutedataname + " (" + error + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatMandatoryDataAbsent(NexoResponseType r, string absolutedataname) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Mandatory data element or structure missing: " + absolutedataname; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatUnexpectedData(NexoResponseType r, string absolutedataname, string error) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Unexpected data element or structure: " + absolutedataname + " (" + error + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatInvalidNumberOfRepetitions(NexoResponseType r, string absolutedataname, string error) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Too many repetitions of the component: " + absolutedataname + " (" + error + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatInvalidOrderOfRepetitions(NexoResponseType r, string absolutedataname, string error) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Invalid repetitions order of the component: " + absolutedataname + " (" + error + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatUnexpectedValue(NexoResponseType r, string absolutedataname, string value) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Unexpected data element value: " + absolutedataname + " (" + value + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatInvalidValueForTheType(NexoResponseType r, string absolutedataname, string value, string type) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = absolutedataname + " Invalid value (" + value + ") for type " + type; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatInvalidEnumeratedValue(NexoResponseType r, string absolutedataname, string value, string type) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = absolutedataname + " Value " + value + " is not part of the enumerated or cluster " + type; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		//public static string MessageFormatRepeatedMessage(NexoResponseType r, string serviceidordeviceidisrepeated, string repeatedid) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Repeated message: " + serviceidordeviceidisrepeated + " (" + repeatedid + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatRepeatedMessage(NexoResponseType r, string repeatedid) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Repeated message: " + repeatedid; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatDataSize(NexoResponseType r, string absolutedataname, string size) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Invalid data size: " + absolutedataname + " (" + size + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatEmptyCluster(NexoResponseType r, string absolutedataname) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Empty cluster: " + absolutedataname; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatUnacceptableValueCombination(NexoResponseType r, string absolutedataname, string value) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Unacceptable value combination: " + absolutedataname + " & " + value; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string MessageFormatUnknownData(NexoResponseType r, string absolutedataname) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.MessageFormat; r.AdditionalResponse = "Unknown data element or structure: " + absolutedataname; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string NotAllowedForbiddenDialogue(NexoResponseType r, string service) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotAllowed; r.AdditionalResponse = "Forbidden request, service (" + service + ") dialogue in progress"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotAllowedForbiddenCombinationOfService(NexoResponseType r, string services) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotAllowed; r.AdditionalResponse = "Forbidden combination of services: " + services; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotAllowedForbiddenMessage(NexoResponseType r, string message) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotAllowed; r.AdditionalResponse = "Forbidden message:" + message; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotAllowedNotAllowedValue(NexoResponseType r, string componentname, string value, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotAllowed; r.AdditionalResponse = componentname + " not allowed value: " + value + " (" + reason + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotAllowedCompletedTransaction(NexoResponseType r) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotAllowed; r.AdditionalResponse = "Completed transaction"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotAllowedInvalidPaymentReservation(NexoResponseType r, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotAllowed; r.AdditionalResponse = "Invalid payment reservation: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotAllowedForbiddenCardReaderSequence(NexoResponseType r, string messagename, string state) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotAllowed; r.AdditionalResponse = messagename + " not allowed in this state: " + state; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotAllowedForbiddenCardReaderAPDURequest(NexoResponseType r, string apdu, string cardbrand) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotAllowed; r.AdditionalResponse = apdu + " APDU request not allowed for the card: " + cardbrand; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string NotFoundTransactionNotFound(NexoResponseType r, string txnid, string component) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotFound; r.AdditionalResponse = "Transaction " + txnid + " not Found in " + component + " link"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotFoundMessageNotFound(NexoResponseType r, string messagecategory, string id) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotFound; r.AdditionalResponse = "Message not found, last " + messagecategory + " has ID " + id; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotFoundReconciliationNotFound(NexoResponseType r, string reconciliationid, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotFound; r.AdditionalResponse = "Reconciliation " + reconciliationid + " not found: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotFoundKeyReferenceNotFound(NexoResponseType r, string keyref) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotFound; r.AdditionalResponse = "Key reference " + keyref + " not found"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotFoundPredefinedMessageReferenceNotFound(NexoResponseType r, string messageid) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotFound; r.AdditionalResponse = "Message reference " + messageid + " not found"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotFoundLanguageNotSupported(NexoResponseType r, string language) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotFound; r.AdditionalResponse = "Language " + language + " not supported"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string NotFoundCardRemoved(NexoResponseType r, string lastmessage) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.NotFound; r.AdditionalResponse = "Card removed by the customer: " + lastmessage; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string PaymentRestriction(NexoResponseType r, string number, string brand) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.PaymentRestriction; r.AdditionalResponse = number + " products not payable by " + brand + " card"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string RefusalAcquirerDecline(NexoResponseType r, string transaction, string acquirer, string reason, string code) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.Refusal; r.AdditionalResponse = transaction + " refused by acquirer: " + acquirer + " - Reason: " + reason + " - Code: " + code; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string RefusalLocalDecline(NexoResponseType r, string transaction, string acquirer, string reason, string code) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.Refusal; r.AdditionalResponse = transaction + " refused locally : " + acquirer + " - Reason: " + reason + " - Code: " + code; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string UnavailableDevice(NexoResponseType r, string devicetype, string infoqualify) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableDevice; r.AdditionalResponse = devicetype + " (" + infoqualify + ") Device unavailable absent or not configured"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string UnavailableDeviceUnavailableDisplayFormat(NexoResponseType r, string format, string feature) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableDevice; r.AdditionalResponse = "Unavailable display format: " + format + " for feature: " + feature; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string UnavailableDeviceUnavailableInputCommand(NexoResponseType r, string command) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableDevice; r.AdditionalResponse = "Unavaible input command: " + command; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string UnavailableDeviceUnavailablePrintingMode(NexoResponseType r, string parameter, string value) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableDevice; r.AdditionalResponse = "Unavaible printing mode: " + parameter + " (" + value + ")"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string UnavailableDeviceUnavailablePINVerificationMethod(NexoResponseType r, string method) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableDevice; r.AdditionalResponse = "Unavaible PIN verification method: " + method; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string UnavailableDeviceUnavailableSoundFormat(NexoResponseType r, string format) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableDevice; r.AdditionalResponse = "Unavailable sound format: " + format; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string UnavailableServiceTooOldProtocolVersion(NexoResponseType r, string saleversion, string serverversion) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableService; r.AdditionalResponse = "Sale protocol version " + saleversion + " too old for server implemented version: " + serverversion; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string UnavailableServiceUnavailableServiceForTheCard(NexoResponseType r, string service, string cardbrand) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableService; r.AdditionalResponse = "Service " + service + " unavailable for card: " + cardbrand; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string UnavailableServiceUnavailableAdministrativeService(NexoResponseType r) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnavailableService; r.AdditionalResponse = "Unavailable administrative service"; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string UnreachableHostHostUnreachable(NexoResponseType r, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnreachableHost; r.AdditionalResponse = "Host unreachable: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
		public static string UnreachableHostNoHostAnswer(NexoResponseType r, string reason) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.UnreachableHost; r.AdditionalResponse = "No answer from host: " + reason; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string WrongPIN(NexoResponseType r, string nbretries, string remainingretries) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = ResultEnumeration.Failure; r.ErrorCondition = ErrorConditionEnumeration.WrongPIN; r.AdditionalResponse = "Wrong PIN: " + nbretries + " retries – Remaining retries: " + remainingretries; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }

		public static string GenericEror(NexoResponseType r, ResultEnumeration result, ErrorConditionEnumeration errorCondition, string addtionalInformation) { if (ResultEnumeration.Success != r.Result) return r.AdditionalResponse; r.Result = result; r.ErrorCondition = errorCondition; r.AdditionalResponse = addtionalInformation; CLog.Add(r.AdditionalResponse, TLog.ERROR); return r.AdditionalResponse; }
	}
}
